### ISSUE TITLE
wpg-install.sh: command not found

### ISSUE THREAD

**Issue by Pilchh** [PoSayDone/.dotfiles_new#2]
I love the look of this setup and decided to give it a go.

When I execute the install script, I get a command not found error for line 29 of `install.sh` where it is attempting to run the `wpg-install.sh` script.

The full error is below"
`install.sh: line 29: wpg-install.sh: command not found`

**Comment by PoSayDone** [comment]
May you check is wpgtk installed on your system?

**Comment by PoSayDone** [comment]
Could you try to use install script again? I think now it would work.

**Comment by Pilchh** [comment]
Yep, looks good now. Thanks.
