### ISSUE TITLE
Package config files inside bspwm directory

### ISSUE THREAD

**Issue by Pilchh** [PoSayDone/.dotfiles_new#3]
Trying the install script, I'm not sure if this has been done intentionally but the dotfiles for a bunch of packages (alacritty, dunst, eww, polybar...) are inside the bspwm folder at `~/.config/bspwm` and are not loaded by the tools.

**Comment by PoSayDone** [comment]
The files should be in the bspwm folder. From the bspwm folder, folders are symlinking to .config for each specific program
Alacrity is deprecated, I am using ST now. I would add it soon. For dunst is not needed to be in .config folder, there is a start script in bspwm/bin. Polybar is deprecated too. Would fix issue with eww

**Comment by PoSayDone** [comment]
Are you sure that there is no eww folder in your .config? That's weird, it should work. ![Screenshot_20221104-101310~2.png](https://user-images.githubusercontent.com/29358657/199894955-d4a09d41-f949-4a73-a423-ebbe4cda3f60.png)

**Comment by Pilchh** [comment]
Alright cool, it looks like eww wasn't installed by the script. I've manually installed it and it's working now. When trying to execute the `autostart` script (I'm assuming that's the main one), I get errors of other unknown commands 
```
autostart: line 7: xdo: command not found
autostart: line 7: xdo: command not found
autostart: line 7: xdo: command not found
discord service running, everything is fine
autostart: line 21: exec: kotatogram-desktop: not found```

**Comment by PoSayDone** [comment]
> Alright cool, it looks like eww wasn't installed by the script. I've manually installed it and it's working now. When trying to execute the `autostart` script (I'm assuming that's the main one), I get errors of other unknown commands
> 
> ```
> autostart: line 7: xdo: command not found
> autostart: line 7: xdo: command not found
> autostart: line 7: xdo: command not found
> discord service running, everything is fine
> autostart: line 21: exec: kotatogram-desktop: not found```
> ```

Xdo was missing in install.sh, so you could install it by yourself or rerun install script.  ```yay -S xdo```
For kotatogram just replace it by telegram-desktop and install usual telegram or install kotatogram-desktop. Also you don't need to run ```autostart``` by your own, bspwm is starting this script on system startup, to run some programs you need, so feel free to edit it.

**Comment by Pilchh** [comment]
Great. I installed xdo myself but thought I'd mention it so you could update the script if necessary. These dotfiles are an excellent foundation for what I'd like to do on my own machine so thank you very much for sharing them!

**Comment by PoSayDone** [comment]
> Great. I installed xdo myself but thought I'd mention it so you could update the script if necessary. These dotfiles are an excellent foundation for what I'd like to do on my own machine so thank you very much for sharing them!

You're very welcome
