### ISSUE TITLE
Symlink configs not working correctly

### ISSUE THREAD

**Issue by Pilchh** [PoSayDone/.dotfiles_new#4]
Hello again!

I've tried to use the install script again on an Arch build however it seems like the symlinked config directories such as `/.config/eww` are not linking properly. 

When the associated programs are launching, they cannot find the config files. The script to automatically start eww is not launching it and when trying to manually start the tool, it gives the following error:
```
ERROR: eww::error_handling_ctx > Failed to initialize eww paths

Caused by:
      Configuration directory /home/pilchh/.config/eww does not exist
```
However, when I look at the `.config` directory, it shows it is symlinked to `/home/pilchh/.config/bspwm/eww`.

Any ideas what is going on?

**Comment by PoSayDone** [comment]
So you don't have eww folder in your .config?

**Comment by PoSayDone** [comment]
Everything works fine for me, maybe you're doing something wrong? Could you try to reinstall dots?

https://user-images.githubusercontent.com/29358657/200080901-638f9262-da50-4a95-a0f2-b0dfc5ef2750.mp4

**Comment by Pilchh** [comment]
I've just tried to reinstall the dots using the `install.sh` script, but I still have the same issue. Looking into it a little more, it looks like an issue with the `bspwm` directory. None of the symlinked folders are in there.

I cleared my `~/.config` directory and re-ran the script to make sure but when the config files are populates, my `bspwm` folder only contains the following:

```
applications
bspwmrc
networkmanager-dmenu
nvchad
picom.conf
rofi
sxhkd
wpg
```

**Comment by PoSayDone** [comment]
Please, delete all folders including .dotfiles_new, bspwm and reinstall dots using this:
```curl -s -L https://raw.githubusercontent.com/PoSayDone/.dotfiles_new/main/install.sh | bash```

**Comment by Pilchh** [comment]
I deleted all the folders in `~/.config` and the `.dotfiles_new` folder and used that curl command, but it still doesn't work.
The bspwm folder in `~/.config/bspwm` still only contains:
```
applications
bspwmrc
networkmanager-dmenu
nvchad
picom.conf
rofi
sxhkd
wpg
```

**Comment by PoSayDone** [comment]
> I deleted all the folders in `~/.config` and the `.dotfiles_new` folder and used that curl command, but it still doesn't work. The bspwm folder in `~/.config/bspwm` still only contains:
> 
> ```
> applications
> bspwmrc
> networkmanager-dmenu
> nvchad
> picom.conf
> rofi
> sxhkd
> wpg
> ```

Okay, I am installing vm now, to test everything

**Comment by PoSayDone** [comment]
Everything works fine on fresh install. I am pretty sure that you are doing something wrong.

https://user-images.githubusercontent.com/29358657/200183230-44e408b4-fa38-46bb-bf0e-83e29f9c9345.mp4

Could you please describe in more detail all the steps you perform during the installation. Also, in which folder do you run the installation command?

**Comment by PoSayDone** [comment]
Accidentally ran the script not in the home folder and I had the same thing that happened to you. The script ```curl -s -L https://raw.githubusercontent.com/PoSayDone/.dotfiles_new/main/install.sh | bash``` should be run in the home folder and the folder .dotfiles_new should also be in the home directory
